In [1]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import pandas as pd

In [3]:
url = "https://raw.githubusercontent.com/AsaelP25/etl-data-pipeline-2510772022/refs/heads/main/data/raw/D_empleados.csv"

In [4]:
df = pd.read_csv(url)

In [5]:
df.head()

  id_empleado          nombre id_departamento fecha_ingreso
0       EM400    Marta Romero             D10    2023-09-12
1       EM401    José Ramírez             D15    2022-09-26
2       EM402   Miguel Romero             D10    2020-02-02
3       EM403     Elena Rivas             D99    2020-01-14
4       EM404  Fernando Rivas             D13    2022-12-25

Exploracion de archivos

In [6]:
df.shape

(136, 4)

In [7]:
df.columns

Index(['id_empleado', 'nombre', 'id_departamento', 'fecha_ingreso'], dtype='object')

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 136 entries, 0 to 135
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id_empleado      136 non-null    object
 1   nombre           136 non-null    object
 2   id_departamento  129 non-null    object
 3   fecha_ingreso    132 non-null    object
dtypes: object(4)
memory usage: 4.4+ KB

In [9]:
df.isnull().sum()

id_empleado        0
nombre             0
id_departamento    7
fecha_ingreso      4
dtype: int64

Limpieza de datos

In [10]:
empleados = df.copy()

In [11]:
empleados.columns = empleados.columns.str.strip().str.lower()

In [12]:
for col in empleados.select_dtypes(include='object').columns:
  empleados[col] = empleados[col].astype(str).str.strip()

In [13]:
empleados = empleados.replace(r'^\s*$',pd.NA, regex=True)

In [14]:
df['fecha_ingreso'] = pd.to_datetime(df['fecha_ingreso'], errors='coerce')

In [15]:
empleados = empleados.drop_duplicates()

Separar datos válidos y rechazados

In [16]:
validos = (
    df['id_empleado'].str.match(r'^EM\d+$', na=False) &
    df['nombre'].notna() &
    df['id_departamento'].str.match(r'^D\d+$', na=False) &
    df['fecha_ingreso'].notna()
)

In [17]:
curated = df[validos].copy()
rejects = df[~validos].copy()

Motivo rechazo

In [18]:
def motivo_error(row):
    if not pd.notna(row['id_empleado']):
        return 'id_empleado nulo'
    if not str(row['id_empleado']).startswith('EM'):
        return 'id_empleado invalido'
    if pd.isna(row['nombre']):
        return 'nombre nulo'
    if not str(row['id_departamento']).startswith('D'):
        return 'departamento invalido'
    if pd.isna(row['fecha_ingreso']):
        return 'fecha invalida'
    return 'otro'

rejects['motivo'] = rejects.apply(motivo_error, axis=1)

Exportacion

In [19]:
curated.to_csv('/content/curated_empleados.csv', index=False)
rejects.to_csv('/content/rejects_empleados.csv', index=False)

Conectar con PostgreSQL Cloud

In [20]:
!pip install sqlalchemy psycopg2-binary

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 43.3 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.11

In [21]:
from sqlalchemy import create_engine

In [22]:
import pandas as pd

In [23]:
database_url = "postgresql://etl_seguros_73l6_user:wRpEP5TIEFqsgtOUDQ8haBIXgMKm6ge0@dpg-d6qu6u14tr6s7380e8p0-a.oregon-postgres.render.com/etl_seguros_73l6"

In [24]:
engine = create_engine(database_url)

In [25]:
test = pd.read_sql("SELECT 1", engine)

In [26]:
print(test)

   ?column?
0         1

Cargar datos en PostgreSQL

In [27]:
curated.to_sql(
    'curated_empleados',
    engine,
    if_exists='append',
    index=False
)

114

In [28]:
rejects.to_sql(
    'rejects_empleados',
    engine,
    if_exists='append',
    index=False
)

22

In [29]:
pd.read_sql(
    "SELECT * FROM curated_empleados LIMIT 10",
    engine
)

  id_empleado           nombre id_departamento fecha_ingreso
0       EM400     Marta Romero             D10    2023-09-12
1       EM401     José Ramírez             D15    2022-09-26
2       EM402    Miguel Romero             D10    2020-02-02
3       EM403      Elena Rivas             D99    2020-01-14
4       EM404   Fernando Rivas             D13    2022-12-25
5       EM405  Diego Hernández             D12    2023-02-03
6       EM406   Adriana Santos             D99    2022-04-22
7       EM408     María Torres             D14    2020-02-04
8       EM409      Paola Rivas             D11    2022-12-20
9       EM410   Andrés Ramírez             D10    2024-01-19

In [30]:
pd.read_sql(
    "SELECT * FROM rejects_empleados LIMIT 10",
    engine
)

,id_empleado,nombre,id_departamento,fecha_ingreso,motivo
0,EM407,Sofía Mendoza,D13,NaT,fecha invalida
1,EM419,Elena Ramírez,D16,NaT,fecha invalida
2,EM422,Luis Romero,None,2020-08-07,departamento invalido
3,EM426,Daniela Martínez,None,2021-05-08,departamento invalido
4,EM447,Luis Mendoza,D14,NaT,fecha invalida
5,EM458,Andrea Martínez,D12,NaT,fecha invalida
6,EM459,Paola Romero,D13,NaT,fecha invalida
7,EM469,Luis Castro,D13,NaT,fecha invalida
8,EM474,Natalia Santos,None,2020-07-14,departamento invalido
9,EM483,Kevin Flores,None,NaT,departamento invalido